### ISSUE TITLE
"Data Source: already exists" Error

### ISSUE THREAD

**Issue by Poag** [pkpio/fitbit-googlefit#84]
Hello,
Although this error looks like #57 that appears to have been resolved, so i am unsure whats occuring here.

```
Traceback (most recent call last):
  File "/chronos/scripts/alex-fittofit/remote.py", line 123, in CreateGoogleFitDataSource
    dataSourceId=self.convertor.GetDataSourceId(dataType)).execute()
  File "/chronos/scripts/alex-fittofit/.venv/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/chronos/scripts/alex-fittofit/.venv/lib/python3.7/site-packages/googleapiclient/http.py", line 920, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://fitness.googleapis.com/fitness/v1/users/me/dataSources/raw%3Acom.google.step_count.delta%3A123456789012%3Afitbit%3Acharge-hr%3Aio.pkp.fbit-gfit?alt=json returned "DataSourceId not found: raw:com.google.step_count.delta:123456789012:fitbit:charge-hr:io.pkp.fbit-gfit". Details: "DataSourceId not found: raw:com.google.step_count.delta:123456789012:fitbit:charge-hr:io.pkp.fbit-gfit">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/chronos/scripts/alex-fittofit/alex-fittofit.py", line 108, in <module>
    main()
  File "/chronos/scripts/alex-fittofit/alex-fittofit.py", line 58, in main
    remote.CreateGoogleFitDataSource(dataType)
  File "/chronos/scripts/alex-fittofit/remote.py", line 130, in CreateGoogleFitDataSource
    body=self.convertor.GetDataSource(dataType)).execute()
  File "/chronos/scripts/alex-fittofit/.venv/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/chronos/scripts/alex-fittofit/.venv/lib/python3.7/site-packages/googleapiclient/http.py", line 920, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 409 when requesting https://fitness.googleapis.com/fitness/v1/users/me/dataSources?alt=json returned "Data Source: raw:com.google.step_count.delta:1059596684745:fitbit:charge-hr:io.pkp.fbit-gfit already exists". Details: "Data Source: raw:com.google.step_count.delta:1059596684745:fitbit:charge-hr:io.pkp.fbit-gfit already exists">
```

**Comment by Poag** [comment]
Nevermind! I had fat fingered my projectid
